### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by Denny09310** [phorks/phork-blazor-reactivity#5]
Hi, I recently came across your repository and found it incredibly helpful for managing the state of blazor without relying on other libraries that might be overkill. I wanted to ask if the repository is still actively maintained and whether you have any plans for future updates. I know that is greatly usable even now, just out of curiosity. I truly appreciate the effort and time you've put into developing and sharing this project. Thank you for your hard work!

**Comment by phorks** [comment]
Hi Denny,
I appreciate your interest in the library.

Even though I'm not currently working with Blazor, I have not abandoned this project. I will be listening to future bug reports and feature requests.

That being said, I believe the library is in a pretty stable state, and I don't currently see any particular aspect of the library that can be further improved. So, unless a feature request comes or source generators become usable in Blazor, I don't have any plans to implement new features.

**Comment by Denny09310** [comment]
Fair enough. Thanks for the quick response. I can't wait to use this library in my next project 🚀
